#! /usr/bin/python

import sys, os, subprocess, datetime, re, shutil

if len(sys.argv) != 2:
   print "usage: deploy BASE_DIR"
   exit(-1)

BASE_DIR = sys.argv[1]


KEEPERS = ['msconfig/Config.py','html/tmp', 'logs']

DIRS_TO_ENSURE = [
   {'dir':'html/tmp',  'perms':'a+rwx'},
   {'dir':'logs',      'perms':'a+rwx'}
]

try:
    sys.path.append(BASE_DIR + "/msconfig")
    from Config import *
except:
    print "Cannot find 'Config.py' in %s/msconfig" % BASE_DIR
    exit(-1)

def listfiles():
    files = [re.sub(r'^./', '', f)
             for f in subprocess.Popen(['find', '.', '-type', 'f', '-print'], stdout=subprocess.PIPE).communicate()[0].split('\n')
             if re.search('.svn', f) == None]
    files = [f for f in files
             if (
	         (re.search(r'~$',f) == None)
	         and (f != 'deploy')
	         and (f != '')
                )]
    return files

def write_filelist(filename, filelist):
   fp = open(filename, "w")
   for file in filelist:
      fp.write(file + "\n")
   fp.close()

write_filelist("/tmp/KEEPERS.list", KEEPERS)    
os.system("(cd %s ; tar -c -v -f /tmp/KEEPERS.tar -T /tmp/KEEPERS.list --ignore-failed-read)" % BASE_DIR)

os.system("(cd %s ; rm -rf *)" % BASE_DIR);

write_filelist("/tmp/FILES.list", listfiles())
os.system("tar -c -f - -T /tmp/FILES.list | ( cd %s ; tar xvf - )" % BASE_DIR)
os.system("(cd %s ; tar xvf /tmp/KEEPERS.tar)" % BASE_DIR)

for dir in DIRS_TO_ENSURE:
    if not os.path.exists(BASE_DIR + "/" + dir['dir']):
       os.mkdir(BASE_DIR + "/" + dir['dir'])

os.system("(cd %s ; chgrp -R fswms .)" % BASE_DIR)

for dir in DIRS_TO_ENSURE:
   os.system("chmod %s %s/%s" % (dir['perms'],BASE_DIR,dir['dir']))
