#! /usr/bin/python

import sys
sys.path.append("../msconfig")
import CGIInjector

MAPFILE = '../msconfig/ews.map'

if CGIInjector.this_computer_is_running_centos():
    MAPSERV = '../cgi-bin/mapserv-5.6.5-CentOS.exe'
else:
    MAPSERV = '../cgi-bin/mapserv-5.6.5.exe'

CGIInjector.mapserv(MAPFILE, MAPSERV)
