#! /usr/bin/python

import sys
sys.path.append("../msconfig")
import CGIInjector

MAPFILE = '../msconfig/ewswcs.map'

if CGIInjector.this_computer_is_running_centos():
    MAPSERV = '../cgi-bin/mapserv-6.0.1-CentOS.exe'
else:
    MAPSERV = '../cgi-bin/mapserv-6.0.1.exe'

CGIInjector.mapserv(MAPFILE, MAPSERV)
