#! /bin/bash

#MAPSERV=/var/fswms.nemac.org/cgi-bin/mapserv-5.6.5.exe
#MAPFILE=/var/fswms.nemac.org/msconfig/ewswgs84.map

MAPSERV=../cgi-bin/mapserv-5.6.5.exe
#MAPSERV=../cgi-bin/mapserv-6.0.0.exe
MAPFILE=../msconfig/ewswgs84.map

if [ "${REQUEST_METHOD}" = "GET" ]; then
  if [ -z "${QUERY_STRING}" ]; then
    QUERY_STRING="map=${MAPFILE}"
  else
    QUERY_STRING="map=${MAPFILE}&${QUERY_STRING}"
  fi
  exec ${MAPSERV}
else
  echo "Sorry, I only understand GET requests."
fi

exit 1
