#! /usr/bin/python

import sys
sys.path.append("../msconfig")
import CGIUtils

MAPFILE = '../msconfig/modisndvi.map'

if CGIUtils.this_computer_is_running_centos():
    MAPSERV = '../cgi-bin/mapserv-5.6.5-CentOS.exe'
else:
    MAPSERV = '../cgi-bin/mapserv-5.6.5.exe'

CGIUtils.mapserv_inject_mapfile(MAPFILE, MAPSERV)