#! /usr/bin/perl

chomp($cwd = `pwd`);
chomp($date = `date`);

$nlines = 25;

$cwd =~ s|^/var/||;
$cwd =~ s|/cgi-bin$||;

$logfilepath = sprintf("/var/log/httpd/%s-access_log", $cwd);

$logtail = `tail -1000 $logfilepath | grep -v 'cgi-bin/log' | tail -$nlines`;

print "Content-type: text/plain\n\n";

printf("last %1d  lines of %s as of %s:\n\n", $nlines, $logfilepath, $date);

print $logtail

