#! /usr/bin/python
import os, re, gd

#Begin category1----------------------------------------------------
layers = [
        {'layerid' : 'EFETAC-NASA_TC_20110124_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110209_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110217_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110225_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110305_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110313_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110321_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110329_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110406_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110414_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110422_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110430_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110508_24'},
        {'layerid' : 'EFETAC-NASA_TC_20110516_24'}]



def next_lid(s):
    strip_zs = s.rstrip('Z')
    if strip_zs:
        return strip_zs[:-1] + chr(ord(strip_zs[-1]) + 1) + 'A' * (len(s) - len(strip_zs))
    else:
        return 'A' * (len(s) + 1)


fo5 = open("truecolors.txt", "w")
start_lid = 'BNJ'

for lid  in layers:
    print lid['layerid']
    string = lid['layerid']
    fo5.write("\t<wmsLayer\n")
    fo5.write("\t\tlid=\""+next_lid(start_lid)+"\"\n")
    fo5.write("\t\tvisible=\"false\"\n")
    fo5.write("\t\turl=\"%(SERVER_URL)s/ewstruecolor?TRANSPARENT=true\"\n")
    fo5.write("\t\tsrs=\"EPSG:3785\"\n")
    fo5.write("\t\tlayers=\""+lid['layerid']+"\"\n")
    fo5.write("\t\tstyles=\"default\"\n")
    fo5.write("\t\tname=\"True Color "+lid['layerid'][-11:]+"\"\n")
    fo5.write("\t\tidentify=\"true\"\n")
    fo5.write("\t\tlegend=\"\"/>\n")
    start_lid = next_lid(start_lid)

fo5.close

