#! /usr/bin/python
import os, re
from datetime import datetime

class Template:
    def __init__(self, file):
        f = open(file, "r")
        self.contents = ""
        for line in f:
            self.contents = self.contents + line
        f.close
    def render(self, dict):
        return self.contents % dict

#Begin category1----------------------------------------------------
dates = [{'date' : '12/28/2010'},
              {'date' : '12/21/2010'},
              {'date' : '12/27/2011'},
              {'date' : '12/20/2011'},
              {'date' : '12/13/2011'},
              {'date' : '12/6/2011'},
              {'date' : '11/29/2011'},
              {'date' : '11/22/2011'},
              {'date' : '11/15/2011'},
              {'date' : '11/8/2011'},
              {'date' : '11/1/2011'},
              {'date' : '10/25/2011'},
              {'date' : '10/18/2011'},
              {'date' : '10/11/2011'},
              {'date' : '10/4/2011'},
              {'date' : '9/27/2011'},
              {'date' : '9/20/2011'},
              {'date' : '9/13/2011'},
              {'date' : '9/6/2011'},
              {'date' : '8/30/2011'},
              {'date' : '8/23/2011'},
              {'date' : '8/16/2011'},
              {'date' : '8/9/2011'},
              {'date' : '8/2/2011'},
              {'date' : '7/26/2011'},
              {'date' : '7/19/2011'},
              {'date' : '7/12/2011'},
              {'date' : '7/5/2011'},
              {'date' : '6/28/2011'},
              {'date' : '6/21/2011'},
              {'date' : '6/14/2011'},
              {'date' : '6/7/2011'},
              {'date' : '5/31/2011'},
              {'date' : '5/24/2011'},
              {'date' : '5/17/2011'},
              {'date' : '5/10/2011'},
              {'date' : '5/3/2011'},
              {'date' : '4/26/2011'},
              {'date' : '4/19/2011'},
              {'date' : '4/12/2011'},
              {'date' : '4/5/2011'},
              {'date' : '3/29/2011'},
              {'date' : '3/22/2011'},
              {'date' : '3/15/2011'},
              {'date' : '3/8/2011'},
              {'date' : '3/1/2011'},
              {'date' : '2/22/2011'},
              {'date' : '2/15/2011'},
              {'date' : '2/8/2011'},
              {'date' : '2/1/2011'},
              {'date' : '1/25/2011'},
              {'date' : '1/18/2011'},
              {'date' : '1/11/2011'},
              {'date' : '1/4/2011'}]


LAYERS = ""
template = Template("drought.wms.tpl")
for dt in dates:
    print dt['date']
    d = datetime.strptime(dt['date'], '%m/%d/%Y')
    LAYERS = LAYERS + template.render(( {
            'YR' : dt['date'],
            'yr' : d.strftime('%Y')[2:]+d.strftime('%m')+d.strftime('%d')
            }  )) + "\n"

f_new = open("test.txt", "w")
f_new.write( LAYERS )
f_new.close()
