#! /usr/bin/python

import sys, re

try:
    from Config import *
except:
    print "Cannot find local settings file 'Config.py'.  You need to create a Config.py file that contains"
    print "settings appropriate for this copy of the FSWMS project.  You can use the file 'Config.py.template'"
    print "as a starting point --- make a copy of that file called 'Config.py', and edit appropriately."
    exit(-1)

class Template:
    def __init__(self, file=None, **args):
        if file is None and 'string' in args:
            self.contents = args['string']
        else:
            f = open(file, "r")
            self.contents = ""
            for line in f:
                self.contents = self.contents + line
            f.close
    def render(self, dict):
        return self.contents % dict

###
### Populate 'layerTitles' dict by reading contents from "layerTitles.txt" file:
###
try:
    f = open("layerTitles.txt", "r")
    layerTitles = {}
    for line in f:
        fields = re.split(r':', line.strip())
        layerTitles[fields[0]] = re.sub(r'^.*/([^/]+)$', '\\1', fields[1])
    f.close()
except:
    print "Can't read file layerTitles.txt; you must run 'makemap' before running this script!"
    sys.exit(-1)

wmsLayerTemplate = Template(string="""
        <wmsLayer
          lid="%(LAYER_LID)s"
          visible="%(LAYER_VISIBLE)s"
          url="%(SERVER_URL)s/ews?TRANSPARENT=true"
          srs="EPSG:3785"
          layers="%(LAYER_NAME)s"
          name="%(LAYER_TITLE)s"
          styles="default" 
          identify="true"
          legend="%(SERVER_URL)s/ewswgs84?SERVICE=WMS&REQUEST=GetLegendGraphic&layer=%(LAYER_NAME)s&VERSION=1.1.1&FORMAT=image/png"/>	
""")

tacsModisChangeDetectionProductLayers = ""
for subgroup in [
    { 'label' : '   Disturbances Since 2003 - 8-Year Baseline',
      'layers' : [
            { 'name' : 'EFETAC-NASA_current',                   'lid' : 'AA',  'visible' : 'true'  },
            { 'name' : 'EFETAC-NASA_previous1',                 'lid' : 'AB',  'visible' : 'false' },
            { 'name' : 'EFETAC-NASA_previous2',                 'lid' : 'AC',  'visible' : 'false' } ] },

    { 'label' : '   Disturbances Since 2010 - 1-Year Baseline',
      'layers' : [
            { 'name' : 'EFETAC-NASA_1YrBaseline_current',       'lid' : 'AD',  'visible' : 'false' },
            { 'name' : 'EFETAC-NASA_1YrBaseline_previous1',     'lid' : 'AE',  'visible' : 'false' },
            { 'name' : 'EFETAC-NASA_1YrBaseline_previous2',     'lid' : 'AF',  'visible' : 'false' } ] },

    { 'label' : '   Disturbances Since 2008 - 3-Year Baseline',
      'layers' : [
            { 'name' : 'EFETAC-NASA_3YrBaseline_current',       'lid' : 'AG',  'visible' : 'false' },
            { 'name' : 'EFETAC-NASA_3YrBaseline_previous1',     'lid' : 'AH',  'visible' : 'false' },
            { 'name' : 'EFETAC-NASA_3YrBaseline_previous2',     'lid' : 'AI',  'visible' : 'false' } ] },

    { 'label' : '   Disturbances Since 2003 - 8-Year Baseline',
      'layers' : [
            { 'name' : 'EFETAC-NASA_AllYrBaseline_current',     'lid' : 'AJ',  'visible' : 'false' },
            { 'name' : 'EFETAC-NASA_AllYrBaseline_previous1',   'lid' : 'AK',  'visible' : 'false' },
            { 'name' : 'EFETAC-NASA_AllYrBaseline_previous2',   'lid' : 'AL',  'visible' : 'false' } ] }
    ]:
    tacsModisChangeDetectionProductLayers = ( tacsModisChangeDetectionProductLayers +
        '      <wmsSubgroup label="' + subgroup['label'] + '">\n' )
    for layer in subgroup['layers']:
        tacsModisChangeDetectionProductLayers = tacsModisChangeDetectionProductLayers + wmsLayerTemplate.render({
                'SERVER_URL'    : SERVER_URL,
                'LAYER_LID'     : layer['lid'],
                'LAYER_NAME'    : layer['name'],
                'LAYER_VISIBLE' : layer['visible'],
                'LAYER_TITLE'   : layerTitles[layer['name']]
                })
    tacsModisChangeDetectionProductLayers = tacsModisChangeDetectionProductLayers + "      </wmsSubgroup>\n"

rsacModisChangeDetectionProductLayers = ""
for subgroup in [    
    { 'label' : '   Disturbances Since 2008 - 3-Year Baseline',
      'layers' : [
            { 'name' : 'RSAC-FHTET_current',                    'lid' : 'AM',  'visible' : 'false' },
            { 'name' : 'RSAC-FHTET_previous1',                  'lid' : 'AN',  'visible' : 'false' },
            { 'name' : 'RSAC-FHTET_previous2',                  'lid' : 'AP',  'visible' : 'false' } ] },
			
			{ 'label' : '   Disturbances Since 2008 - 5-Year Baseline',
      'layers' : [
            { 'name' : 'RSAC-FHTET_5YrBaseline_current',        'lid' : 'AQ',  'visible' : 'false' },
            { 'name' : 'RSAC-FHTET_5YrBaseline_previous1',      'lid' : 'AR',  'visible' : 'false' },
            { 'name' : 'RSAC-FHTET_5YrBaseline_previous2',      'lid' : 'AS',  'visible' : 'false' } ] }
### 
### Hey Matt:
###    The following RSAC layers are now available to be added, whenever you're ready!:
###       RSAC-FHTET_3YrBaseline_previous2
###       RSAC-FHTET_3YrBaseline_previous1
###       RSAC-FHTET_3YrBaseline_current
###       RSAC-FHTET_5YrBaselineBD_previous1
###       RSAC-FHTET_5YrBaselineBD_current
###       RSAC-FHTET_5YrBaselineBD_previous2
###       RSAC-FHTET_3YrBaselineBD_previous2
###       RSAC-FHTET_3YrBaselineBD_previous1
###       RSAC-FHTET_3YrBaselineBD_current
###       RSAC-FHTET_5YrBaseline_current
###       RSAC-FHTET_5YrBaseline_previous2
###       RSAC-FHTET_5YrBaseline_previous1
###   --Mark
### 
    ]:
    rsacModisChangeDetectionProductLayers = ( rsacModisChangeDetectionProductLayers +
        '      <wmsSubgroup label="' + subgroup['label'] + '">\n' )
    for layer in subgroup['layers']:
        rsacModisChangeDetectionProductLayers = rsacModisChangeDetectionProductLayers + wmsLayerTemplate.render({
                'SERVER_URL'    : SERVER_URL,
                'LAYER_LID'     : layer['lid'],
                'LAYER_NAME'    : layer['name'],
                'LAYER_VISIBLE' : layer['visible'],
                'LAYER_TITLE'   : layerTitles[layer['name']]
                })
    rsacModisChangeDetectionProductLayers = rsacModisChangeDetectionProductLayers + "      </wmsSubgroup>\n"


    
template = Template("ews_config.tpl.xml")

f = open("../html/view/config/ews_config.xml", "w")
f.write(template.render( {
            'SERVER_URL'                            : SERVER_URL,
            'VIEWER_DEPLOY_DIR_URL'                 : VIEWER_DEPLOY_DIR_URL,
            'TACS_MODIS_CHANGE_DETECTION_PRODUCT_LAYERS' : tacsModisChangeDetectionProductLayers,
			'RSAC_MODIS_CHANGE_DETECTION_PRODUCT_LAYERS' : rsacModisChangeDetectionProductLayers
            }))
f.close()
